services:
  frontend:
    image: ghcr.io/bishko86/descartes-square-frontend:latest
    container_name: descartes-frontend
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network
      - shared-proxy
    labels:
      - "com.centurylinklabs.watchtower.scope=descartes"

  api:
    image: ghcr.io/bishko86/descartes-square-api:latest
    container_name: descartes-api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CONNECTION: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/descartes-square?authSource=admin
      PORT: 3000
    depends_on:
      - mongodb
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.scope=descartes"

  mongodb:
    image: mongo:7
    container_name: descartes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
  shared-proxy:
    external: true
