name: API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout NestJS API app
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      # Determine base/head for Nx affected
      - name: Compute base/head SHAs
        id: shas
        run: |
          git fetch origin ${{ github.event.repository.default_branch }} --depth=1 || true
          echo "BASE_SHA=$(git merge-base origin/${{ github.event.repository.default_branch }} HEAD)" >> $GITHUB_OUTPUT
          echo "HEAD_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Detect if api is affected
        id: affected
        run: |
          AFFECTED=$(npx nx print-affected --base=${{ steps.shas.outputs.BASE_SHA }} --head=${{ steps.shas.outputs.HEAD_SHA }} --select=projects)
          echo "affected=$AFFECTED" >> $GITHUB_OUTPUT
          if echo "$AFFECTED" | tr ',' '\n' | grep -xq 'api'; then
            echo "api_changed=true" >> $GITHUB_OUTPUT
            echo "api is affected: $AFFECTED"
          else
            echo "api_changed=false" >> $GITHUB_OUTPUT
            echo "api not affected. Skipping lint/build."
          fi

      - name: Lint API
        if: steps.affected.outputs.api_changed == 'true'
        run: npx nx lint api

      - name: Build API
        if: steps.affected.outputs.api_changed == 'true'
        run: npx nx build api
